"use client";

import Link from "next/link";
import { useApp } from "@/lib/store/provider";
import { ActionCard } from "@/components/ActionCard";
import { Button, Card, Disclaimer, EmptyState, SectionTitle } from "@/components/ui";
import { latestSnapshot } from "@/lib/data/bundle";
import { todayISO } from "@/lib/today";
import { Partners } from "@/components/Partners";

export default function TodayPage() {
  const { ready, hasData, bundle, plan, loadDemoSeed, mode } = useApp();

  if (!ready) return <p className="text-sm text-cloud-faint">Loading…</p>;

  // Soft gate: once the user has started, prompt the starter tools once before
  // showing the plan. They can set up, mark "already use it", or skip — then continue.
  if (hasData && !bundle.partnersAcknowledged) {
    return <Partners mode="gate" />;
  }

  if (!hasData) {
    return (
      <div className="space-y-4">
        <SectionTitle
          title="Welcome"
          subtitle="Start with the synthetic demo, or enter your own information."
        />
        <EmptyState
          title="No data yet"
          body={
            mode === "demo"
              ? "Load a clearly-labeled synthetic founder to explore the full loop, or start fresh onboarding to enter your own numbers."
              : "Start onboarding to enter your own information. It's stored securely to your account."
          }
          action={
            <div className="flex flex-col gap-2">
              {mode === "demo" ? <Button onClick={loadDemoSeed}>Load synthetic demo</Button> : null}
              <Link href="/onboarding">
                <Button variant={mode === "demo" ? "secondary" : "primary"} className="w-full">
                  Start {mode === "demo" ? "fresh " : ""}onboarding
                </Button>
              </Link>
            </div>
          }
        />
        <Disclaimer>
          Educational only — not legal, tax, or financial advice. No credit scores or guarantees are
          produced.
        </Disclaimer>
      </div>
    );
  }

  const snapshot = latestSnapshot(bundle);
  const total = plan.thirtyDayPlan.length;
  const done = plan.thirtyDayPlan.filter((a) => a.status === "complete").length;
  const freshnessDays = snapshot ? daysSince(snapshot.asOf) : null;

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-bold text-cloud">Today</h1>
        <p className="text-sm text-cloud-muted">Your next steps, in order.</p>
      </div>

      {/* Snapshot freshness + progress */}
      <div className="grid grid-cols-2 gap-3">
        <Card className="p-3">
          <p className="text-xs text-cloud-faint">Snapshot</p>
          {snapshot ? (
            <>
              <p className="text-sm font-semibold text-cloud">{snapshot.asOf}</p>
              <p className="text-xs text-cloud-muted">
                {freshnessDays === 0 ? "Updated today" : `${freshnessDays} day(s) old`}
              </p>
            </>
          ) : (
            <p className="text-sm text-cloud-muted">None yet</p>
          )}
        </Card>
        <Card className="p-3">
          <p className="text-xs text-cloud-faint">30-day progress</p>
          <p className="text-sm font-semibold text-cloud">
            {done} / {total} complete
          </p>
          <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-ink-soft">
            <div
              className="h-full rounded-full bg-teal"
              style={{ width: total ? `${(done / total) * 100}%` : "0%" }}
            />
          </div>
        </Card>
      </div>

      {plan.notices.length > 0 ? (
        <Card className="border-warn/40 bg-warn/5">
          {plan.notices.map((n, i) => (
            <p key={i} className="text-sm text-warn">
              {n}
            </p>
          ))}
        </Card>
      ) : null}

      <div>
        <SectionTitle title="Your 3 priorities now" subtitle="Chosen by transparent rules — not AI." />
        <div className="space-y-3">
          {plan.priorities.length === 0 ? (
            <EmptyState
              title="No current priorities"
              body="You've handled the current priorities. Check My Plan for your full 30-day sequence."
            />
          ) : (
            plan.priorities.map((a, i) => <ActionCard key={a.actionId} action={a} rank={i + 1} />)
          )}
        </div>
      </div>

      {snapshot && freshnessDays !== null && freshnessDays > 7 ? (
        <Card className="border-teal/30">
          <p className="text-sm text-cloud">Your snapshot is over a week old.</p>
          <Link href="/finances" className="mt-2 inline-block text-sm font-medium text-teal underline">
            Update your finances →
          </Link>
        </Card>
      ) : null}

      <Disclaimer>
        Actions and priorities are generated by a versioned deterministic rules engine
        (v{plan.engineVersion}). Completions you record are your own reports unless independently
        verified.
      </Disclaimer>
    </div>
  );
}

function daysSince(iso: string): number {
  const then = Date.parse(iso + "T00:00:00Z");
  const now = Date.parse(todayISO() + "T00:00:00Z");
  return Math.max(0, Math.round((now - then) / (1000 * 60 * 60 * 24)));
}
